openapi: 3.2.0
info:
  description: Manage Device Types
  title: CarbonHub Device Types API
  version: 1.0.0
servers:
- url: https://api.validere.io
security:
- Staging: []
- Integration: []
- Local: []
tags:
- description: Manage Device Types
  name: Device Types
paths:
  /app/v1/device_types:
    get:
      operationId: list_device_types
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceTypeList'
          description: successful operation
      summary: Get Device Type List
      tags:
      - Device Types
components:
  schemas:
    DeviceTypeList:
      items:
        $ref: '#/components/schemas/DeviceType'
      type: array
    DeviceTypeAttribute:
      properties:
        data_type:
          $ref: '#/components/schemas/AttributeTypes'
        description:
          type: string
        id:
          type: string
        name:
          type: string
      type: object
    DeviceType:
      properties:
        attributes:
          items:
            $ref: '#/components/schemas/DeviceTypeAttribute'
          type: array
        id:
          type: string
        name:
          type: string
      type: object
    AttributeTypes:
      type: string
      enum:
      - number
      - string
      - geo_point
      - boolean
      - integer
      - pick-list
      - multi-pick-list
      - number-array
      - lookup
      - date
      - date-time
      - file
